version: 2
jobs:
  py367:
    working_directory: ~/matminer
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
#      - restore_cache:
#          keys:
#          - py367-dependencies-{{ checksum "requirements.txt" }}
#          # fallback to using the latest cache if no exact match is found
#          - py367-dependencies-
      - run:
          name: Set up env via pip
          command: |
            export CI=circle
            python3 -m venv test_env
            . test_env/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            cd ~/matminer
            echo "running optional install"
            pip install -r requirements-optional.txt
            echo "running requirements install"
            pip install -r requirements.txt
            echo "running install matminer"
            pip install -e .
            python setup.py test
      - save_cache:
          paths:
          - ./test_env
          key: py367-dependencies-{{ checksum "requirements.txt" }}
  py371:
    working_directory: ~/matminer
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - py371-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - py371-dependencies-
      - run:
          name: Set up env via pip
          command: |
            export CI=circle
            python3 -m venv test_env
            . test_env/bin/activate
            pip install --quiet --upgrade pip
            pip install --quiet --upgrade setuptools
            cd ~/matminer
            pip install --quiet -r requirements.txt
            pip install --quiet -r requirements-optional.txt
            pip install --quiet -e .
            python setup.py test
      - save_cache:
          paths:
            - ./test_env
          key: py371-dependencies-{{ checksum "requirements.txt" }}


workflows:
  version: 2
  build_and_test:
    jobs:
      - py367
      - py371